//temp before db
const locations = [
  {
    name: "Fellow Traveler",
    id: "962a3735-cdb8-43b7-8491-e58706601678",
    lat: 39.653559457378044,
    long: -104.98779125852745,
    category: "Restaurant",
    cuisine: ["American"],
    tags: ["american", "modern"],
    dateUpdated: "07/09/2024",
    menu: [
      "fried cornbread red pepper jam",
      "mac n' cheese cellantani noodles tossed in cashew cream sauce topped w/ cornbread crumbles & green onions",
      "sweet garlic cauliflower fried cauliflower tossed in a sweet ginger garlic asian sauce",
      "chilaquiles tofu, corn chips, green chile, pinto beans, chipotle crema, avocado, onions & cilantro",
      "summer salad kale veg mix tossed in a vinaigrette and topped w/ sunflower seeds and craisins",
      "seaside avocado tacos fried avocado, slaw, nori cilantro cashew crema",
      "deep south broadway burrito vegan sausage, tofu, potatoes, beans, smothered in green chile and topped with chipotle creme, onions & cilantro, and avocado",
      "pineapple fried rice pineapple, rice, tofu, pickled carrot & daikon, green onions, topped with jalapeño, fried onions, and sesame seeds",
      "aloo gobi cauliflower, potato, coconut curry, rice",
      "banh mi sandwich tofu, miso aioli, cucumbers, cilantro, chili oil, sunflower shoots, pickled carrots, daikon & jalapeños, or try it as a rice bowl. served with a side of fries",
      "el borracho carolina gold bbq smoked jackfruit sandwich w/pickles, onion strings & mayo on a potato bun served w/house cut fries",
      "falafel wrap fried chickpea fritter, pickled turnips, dill pickles, cucumber, tzatziki, fries, sambar & Lebanese slaw served w/ house cut fries",
      "poutine housecoat fries covered in gravy & cashew crea",
      "beans & rice an hour’s worth of food",
      "darlene's downeast chocolate cake warm chocolate cake, oreo butter cream, peanut butter glaze, coconut sorbet",
      "lemon or mango rice pudding coconut dulce de leche, cookie crumble, rotating fruit compote",
      "vanilla ice cream try w/ an amaro",
      "chilaquiles tofu, corn tortillas, green chile, pinto beans, chipotle crema, avocado, onions & cilantro",
      "deep south broadway burrito vegan sausage, tofu, potatoes, beans, chipotle crema, avocado, onions & cilantro smothered in green chile",
      "breakfast sandwich tofu, tempeh strips, kale, tomato & chipotle crema on sourdough served with home fries",
      "breakfast tacos tofu, seasoned home fries, avocado, chipotle cream & pico de Gallo",
      "spanish toast plate one piece avocado toast w/kale, grapefruit & pear on sourdough, one piece pan con tomato, w/ garlic, olive oil, tomato & salt on sourdough",
      "full English tofu, home fries, tempeh strips, sausage patty, grilled tomato, grill mushrooms, baked beans & toast",
      "cinnamon cornbread sticks served w/ maple syrup",
      "biscuits & gravy biscuits baked in house, w/ an irish style brown gravy, served with scrambled tofu, home fries & topped with green onion",
      "waffle served with maple syrup and vegan butter",
      "darlene style waffle oreo butter cream, peanut butter glaze, coconut, maple syrup",
      "chicken fried cauliflower & waffle served w/ maple or spicy maple",
      "scrambled tofu",
      "home fries",
      "avocado",
      "sausage",
      "tempeh strips",
      "toast",
      "tortilla",
      "biscuit",
    ],
    plantBasedLevel: "full",
    address: "3487 S Broadway, Englewood, CO 80113",
    userRating: 4.5,
    editorRating: 5,
  },
  {
    name: "Somebody People",
    id: "7d302859-3be4-4541-9a77-2d2475c203ba",
    lat: 39.69776103252339,
    long: -104.98760781409766,
    category: "Restaurant",
    cuisine: ["Italian"],
    tags: ["american", "italian", "modern"],
    dateUpdated: "07/09/2024",
    menu: [
      "seedlip grove | blueberry hibiscus | lemongrass | lime",
      "pineapple | coconut lime | cinnamon",
      "dhos juniper | lyres Italian orange | citrus cordial | birch n/a sparkling | tonic",
      "arette tequila | triple sec faccia brutto | ginger cucumber | green pepper celery | lemon",
      "mell vodka | lychee strawberry | pistachio | lemon cardamom",
      "mel vodka | asker gin norden aquavit celery | olive brine",
      "four roses bourbon sweet vermouth | ginger lemon | chocolate",
      "rayu mezcal | arette tequila kalani coconut | charaeu aloe matcha | pineapple lime | salt",
      "askur gin contratto bitter | amaro montenegro | cantaloupe lemon | salt",
      "flor de cana rum | fino sherry velvet falernum | watermelon lime | peychauds",
      "uncle nearest rye pineapple amaro | banana lavender | ipa | lemon",
      "mell vodka mr. black espresso liqueur demerara | huck espresso",
      "orange | pineapple | lemonade 6 oz",
      "cucumber, green apple, celery 8 oz",
      "montenegro | ciociaro | foro",
      "l'atzar, cava",
      "steinbock, n/a sparkling",
      "somebody's vino, house chardonnay blend",
      "wiseguy, sauvignon blanc",
      "rodica, malvazija",
      "olivares, garnacha",
      "esoterico, zibibbo blend",
      "somebody's vino, house grenache / syrah",
      "domaine begude, pinot noir",
      "heliotropes, cinsault blend",
      "minimum, sangiovese blend",
      "apres pilsner crooked stave 16 oz",
      "juicy east IPA crooked stave 16 oz",
      "wild state honey crisp imperial cider 12 oz",
      "petite peach sour crooked stave 16 oz",
      "half acre daisy cutter pale ale 16 oz can",
      "oakshire amber ale 16 oz can",
      "great divide tangerine riot fruited IPA 12 oz can",
      "denver beer company princess yum yum 12 oz can",
      "palisade peach",
      "blue sunshine strawberry lavender vanilla 12 oz can",
      "grilled sourdough served with rotating seasonal spread (gf on request +$1) may contain nuts",
      "arancini asparagus | tonnato meyer lemon",
      "shaved celery dates | smoked almond | dill",
      "esoterra farm salad radish | red onion | sourdough croutons | red wine vinaigrette",
      "torn cucumber lime and fermented black bean | spicy cashew | herbs",
      "marinated plums celtuce | radish | sweet lime vinaigrette",
      "roasted broccoli ajo blanco | almonds | sumac parsley mint salsa",
      "cabbage bagna cauda | toasted hazelnuts | chives",
      "roasted cauliflower vadouvan spice | pistachio pesto | salsa verde",
      "mushroom rice garlic | hemp cream | chive",
      "zucca creamed corn | toasted nori meyer lemon brown butter",
      "tagliatelle summer squash zucchini | oregano | chili flakes",
      "rigatoni summer tomato | confit garlic basil | red chili",
      "tiramisu coffee | vanilla | amaro",
      "pineapple upside down cake lime whip | luxardo cherry",
      "panna cotta seasonal toppings (GF)",
      "chocolate chip cookie",
      "gluten free choc chip cookie (gf)",
      "espresso",
      "americano",
      "matcha",
      "cappuccino",
      "latte",
      "legendary spirit tea ambrosia black",
      "rosella",
      "chamomile",
      "crescent green",
    ],
    plantBasedLevel: "full",
    address: "1165 S Broadway #104, Denver, CO 80210",
    userRating: 4.7,
    editorRating: 4,
  },
  {
    name: "Next Level Burger",
    id: "6ad2152a-51dc-4bd2-bb51-6f8a2845d27e",
    lat: 39.68149629359531,
    long: -104.96921136411149,
    category: "Restaurant",
    cuisine: ["Fast Food", "American"],
    tags: ["american", "fast food", "burgers", "comfort"],
    dateUpdated: "07/09/2024",
    menu: [
      "Classic Burger",
      "American Chzburger",
      "Fire Chzburger",
      "Beyond Burger",
      "Maverick Burger",
      "Ghost Pepper Popper Burger",
      "Beyond Fire Burger",
      "PubChz Burger",
      "Signature Burger",
      "Socal Burger",
      "Blue Bbq Burger",
      "Chipotle Burger",
      "Crispy Chik’n Burger",
      "Fire Chik'n Burger",
      "Chik’n Bacon Ranch Burger",
      "Buffalo Chik'n Burger",
      "Spicy Stacked Chik'n",
      "Beyond Animal Burger",
    ],
    plantBasedLevel: "full",
    address: "1605 E Evans Ave, Denver, CO 80210",
    userRating: 4.3,
    editorRating: 4,
  },
  {
    name: "Mora Pizza Denver",
    id: "31bb55c8-9888-442b-9fcf-4fbb6488dd51",
    lat: 39.740182097479554,
    long: -104.95481190303029,
    category: "Grocery",
    cuisine: ["Pizza", "Italian"],
    tags: ["pizza"],
    dateUpdated: "07/09/2024",
    menu: [
      "Specialty Slice: Pepperoni",
      "Cheesy Knots",
      'Meatball Parm Pizza (18")',
      'Cheese Pizza (18")',
      "Garlic Parmesan Wings",
      "Garlic Knots",
      "Buffalo Wings",
      "BBQ Wings",
      "Pepperoni Knots",
      "Buffalo Knots",
      "Vegan Meatballs",
      "Cheesy Vegan Meatballs",
      "Bar Pizzas",
    ],
    plantBasedLevel: "partial",
    address: "2700 E Colfax Ave, Denver, CO 80206",
    userRating: 3.9,
    editorRating: 4,
  },
];

export default defineEventHandler(() => {
  return locations;
});
